defaults:
  #languages
  - scope:
      path: ""
    values:
      lang: "en"
      layout: default
  - scope:
      path: "fr"
    values:
      lang: "fr"

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  toc_levels: 1..3
      
markdown: kramdown
